"""initial

Revision ID: a65e06cd2666
Revises:
Create Date: 2017-07-26 21:15:37.500046

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'a65e06cd2666'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('vintage', sa.Date(), nullable=True),
    sa.Column('resolution', sa.Float(), nullable=True),
    sa.Column('url_template', sa.Text(), nullable=True),
    sa.Column('bbox', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326), nullable=True),
    sa.Column('min_zoom', sa.Integer(), nullable=True),
    sa.Column('max_zoom', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_bbox'), 'sources', ['bbox'], unique=False)
    op.create_index(op.f('ix_sources_slug'), 'sources', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sources_slug'), table_name='sources')
    op.drop_index(op.f('ix_sources_bbox'), table_name='sources')
    op.drop_table('sources')
    # ### end Alembic commands ###
